/**
 * Fixture generator.
 *
 * This file plays the part of the backend's database contents. It builds a
 * CONNECTED graph of documents rather than independent random rows:
 *
 *   PurchaseOrder -> GoodsReceipt -> StockMove(+) -> SupplierBill -> Payment
 *   SalesOrder    -> Delivery     -> StockMove(-) -> CustomerInvoice -> Payment
 *   every posted invoice / payment / delivery -> JournalEntry
 *   every state change -> AuditEvent
 *
 * Building it this way is the point. If the fixtures were random, the UI could
 * show a "related documents" panel that is decorative. Because they are
 * generated by walking the real business process, the traceability in the UI is
 * genuine, and any modelling mistake shows up immediately as data that will not
 * link.
 */

import type {
  AuditEvent,
  Customer,
  CustomerInvoice,
  Delivery,
  DeliveryLine,
  DocumentRef,
  GoodsReceipt,
  InventoryAdjustment,
  InvoiceLine,
  InvoiceStatus,
  JournalEntry,
  JournalLine,
  Money,
  Payment,
  PaymentAllocation,
  Product,
  ProductType,
  PurchaseOrder,
  PurchaseOrderLine,
  PurchaseOrderStatus,
  SalesOrder,
  SalesOrderLine,
  SalesOrderStatus,
  StockMove,
  Supplier,
  Uom,
  UserRef,
} from '@/domain';
import { money } from '@/domain';
import { add, multiply, percentOf, subtract, sum, zero } from '@/lib/money';
import { createRng, REFERENCE_TODAY, addDays, daysAgo, toISODate, toISODateTime } from './rng';
import { ACCOUNT_BY_CODE, CASH_ACCOUNTS, CATEGORIES, PAYMENT_TERMS, SALES_REPS, USERS, WAREHOUSES } from './reference';

const rng = createRng(20260814);

const VAT_RATE = 21; // Standard rate for the modelled jurisdiction.

const ref = (u: (typeof USERS)[number]): UserRef => ({ id: u.id, name: u.name });
const U = Object.fromEntries(USERS.map((u) => [u.id, ref(u)])) as Record<string, UserRef>;

const pad = (n: number, width = 4) => String(n).padStart(width, '0');

function stamps(createdAt: Date, by: UserRef, updatedAt: Date = createdAt) {
  return {
    createdAt: toISODateTime(createdAt),
    createdBy: by,
    updatedAt: toISODateTime(updatedAt),
    updatedBy: by,
  };
}

// ===========================================================================
// PRODUCTS
// ===========================================================================
// [sku, name, categoryId, uom, salesPrice, costPrice, reorderPoint, reorderQty]
type ProductSeed = [string, string, string, Uom, number, number, number, number];

const PRODUCT_SEEDS: ProductSeed[] = [
  ['CBL-1025', 'Twin & Earth Cable 2.5mm², 100m Drum', 'cat-1', 'unit', 148.5, 92.4, 40, 120],
  ['CBL-1015', 'Twin & Earth Cable 1.5mm², 100m Drum', 'cat-1', 'unit', 96.0, 58.75, 50, 150],
  ['CBL-2040', 'SWA Armoured Cable 4mm² 3-Core, 50m', 'cat-1', 'unit', 312.0, 208.5, 15, 40],
  ['CBL-3006', 'Flexible Cord 0.75mm² 3-Core, 100m', 'cat-1', 'unit', 62.4, 37.2, 60, 200],
  ['CBL-4100', 'Cat6 UTP Data Cable, 305m Box', 'cat-1', 'box', 184.0, 118.0, 20, 60],
  ['CBL-5012', 'Earth Bonding Cable 6mm² Green/Yellow, 50m', 'cat-1', 'unit', 78.9, 47.3, 30, 80],

  ['MCB-0616', 'MCB Type B 16A Single Pole', 'cat-2', 'unit', 8.4, 4.15, 200, 600],
  ['MCB-0632', 'MCB Type B 32A Single Pole', 'cat-2', 'unit', 9.75, 4.85, 150, 500],
  ['MCB-0740', 'MCB Type C 40A Triple Pole', 'cat-2', 'unit', 34.6, 19.4, 60, 180],
  ['RCD-0863', 'RCD 63A 30mA Double Pole', 'cat-2', 'unit', 46.2, 26.8, 45, 120],
  ['RCB-0932', 'RCBO 32A 30mA Type A', 'cat-2', 'unit', 41.85, 24.6, 70, 200],
  ['CU-1012', 'Consumer Unit 12-Way Metal Enclosure', 'cat-2', 'unit', 128.0, 76.5, 25, 60],
  ['SPD-1101', 'Surge Protection Device Type 2', 'cat-2', 'unit', 96.4, 58.9, 20, 50],
  ['FUS-1220', 'HRC Fuse Link 20A', 'cat-2', 'unit', 6.2, 2.95, 250, 800],

  ['LED-2018', 'LED Panel 600x600 36W 4000K', 'cat-3', 'unit', 42.5, 24.75, 80, 240],
  ['LED-2024', 'LED Batten 5ft 45W IP20', 'cat-3', 'unit', 36.8, 20.4, 90, 250],
  ['LED-2032', 'LED Floodlight 100W IP65', 'cat-3', 'unit', 58.9, 33.2, 40, 120],
  ['LED-2040', 'LED Downlight Fire-Rated 6W Dimmable', 'cat-3', 'unit', 14.6, 7.85, 300, 900],
  ['LED-2055', 'Emergency Exit Sign LED Maintained', 'cat-3', 'unit', 44.0, 26.1, 35, 100],
  ['LMP-2101', 'High Bay LED 150W 5000K', 'cat-3', 'unit', 172.0, 108.4, 18, 50],

  ['ENC-3010', 'Steel Enclosure IP66 400x300x200', 'cat-4', 'unit', 88.5, 52.9, 25, 70],
  ['TRK-3020', 'PVC Trunking 100x50mm, 3m Length', 'cat-4', 'unit', 18.4, 9.75, 120, 400],
  ['CDT-3030', 'Galvanised Conduit 20mm, 3m Length', 'cat-4', 'unit', 11.2, 5.6, 150, 500],
  ['TRY-3040', 'Cable Tray 300mm Medium Duty, 3m', 'cat-4', 'unit', 46.9, 27.3, 40, 120],
  ['BOX-3050', 'Adaptable Box 100x100x50 PVC', 'cat-4', 'unit', 4.35, 1.98, 400, 1200],
  ['GLD-3060', 'Cable Gland Kit M20 Brass, Pack of 10', 'cat-4', 'box', 22.6, 12.4, 80, 250],

  ['TLS-4010', 'Insulated Screwdriver Set 7-Piece VDE', 'cat-5', 'unit', 54.0, 31.5, 30, 80],
  ['TLS-4020', 'Cable Cutter Ratchet 32mm', 'cat-5', 'unit', 68.4, 41.2, 20, 50],
  ['TLS-4030', 'Digital Multimeter CAT III 600V', 'cat-5', 'unit', 112.0, 68.9, 25, 60],
  ['TLS-4040', 'Crimping Tool Ratchet 0.5-6mm²', 'cat-5', 'unit', 47.5, 27.8, 30, 90],
  ['CON-4110', 'Wago Lever Connector 3-Way, Box of 100', 'cat-5', 'box', 38.9, 21.6, 100, 300],
  ['CON-4120', 'Cable Ties 200mm Black, Pack of 1000', 'cat-5', 'box', 16.4, 7.9, 120, 400],
  ['CON-4130', 'Insulation Tape PVC 19mm, Pack of 10', 'cat-5', 'box', 9.8, 4.35, 200, 600],
  ['CON-4140', 'Terminal Block 16A 12-Way Strip', 'cat-5', 'unit', 5.6, 2.4, 250, 700],
];

const SERVICE_SEEDS: [string, string, number][] = [
  ['SRV-9010', 'Next-Day Delivery Surcharge', 45.0],
  ['SRV-9020', 'Site Survey & Take-off', 320.0],
  ['SRV-9030', 'Cable Cutting & Reeling Service', 28.0],
];

export const PRODUCTS: Product[] = [
  ...PRODUCT_SEEDS.map(([sku, name, categoryId, uom, salesPrice, costPrice, rp, rq], i): Product => ({
    id: `p-${pad(i + 1, 3)}`,
    sku,
    name,
    type: 'stockable' as ProductType,
    categoryId,
    categoryName: CATEGORIES.find((c) => c.id === categoryId)!.name,
    uom,
    barcode: `50${pad(190000 + i * 137, 11)}`,
    salesPrice: money(salesPrice),
    costPrice: money(costPrice),
    costingMethod: 'average',
    reorderPoint: rp,
    reorderQuantity: rq,
    active: true,
    ...stamps(daysAgo(365), U['u-1']!),
  })),
  ...SERVICE_SEEDS.map(([sku, name, price], i): Product => ({
    id: `p-s${pad(i + 1, 2)}`,
    sku,
    name,
    type: 'service' as ProductType,
    categoryId: 'cat-6',
    categoryName: 'Services',
    uom: 'unit',
    salesPrice: money(price),
    costPrice: money(0),
    costingMethod: 'standard',
    reorderPoint: 0,
    reorderQuantity: 0,
    active: true,
    ...stamps(daysAgo(365), U['u-1']!),
  })),
];

const STOCKABLE = PRODUCTS.filter((p) => p.type === 'stockable');

// ===========================================================================
// PARTIES
// ===========================================================================

const CUSTOMER_SEEDS: [string, string, string, keyof typeof PAYMENT_TERMS, number][] = [
  ['Halvorsen Electrical Contractors', 'Oslo', 'NO', 'net_30', 150_000],
  ['Brightway Facilities Management', 'Manchester', 'GB', 'net_45', 80_000],
  ['Nordic Build Group AB', 'Malmö', 'SE', 'net_30', 200_000],
  ['Delta Site Services BV', 'Utrecht', 'NL', 'net_30', 60_000],
  ['Kestrel Retail Fitouts', 'Birmingham', 'GB', 'net_15', 40_000],
  ['Vantage Data Centres SARL', 'Lyon', 'FR', 'net_60', 350_000],
  ['Meyer Industrieservice GmbH', 'Düsseldorf', 'DE', 'net_30', 120_000],
  ['Coastline Marine Fitters', 'Rotterdam', 'NL', 'net_30', 45_000],
  ['Argent Property Maintenance', 'London', 'GB', 'net_30', 70_000],
  ['Solaris Renewables Ltd', 'Bristol', 'GB', 'net_45', 90_000],
  ['Pemberton Housing Trust', 'Leeds', 'GB', 'net_60', 55_000],
  ['Ridge & Molloy Electrical', 'Dublin', 'IE', 'net_30', 35_000],
  ['Aurora Hotels Group', 'Amsterdam', 'NL', 'net_45', 110_000],
  ['Westfield Cold Storage', 'Antwerp', 'BE', 'net_30', 65_000],
  ['Lumen Shopfitting Services', 'Ghent', 'BE', 'net_15', 25_000],
  ['Trident Engineering Works', 'Hamburg', 'DE', 'net_30', 140_000],
  ['Castille Construction SA', 'Toulouse', 'FR', 'net_45', 95_000],
  ['Orbit Facilities Nordic', 'Copenhagen', 'DK', 'net_30', 75_000],
];

export const CUSTOMERS: Customer[] = CUSTOMER_SEEDS.map(([name, city, country, terms, credit], i) => ({
  id: `c-${pad(i + 1, 3)}`,
  code: `CUST-${pad(i + 1)}`,
  name,
  type: 'customer' as const,
  email: `accounts@${name.toLowerCase().replace(/[^a-z]+/g, '').slice(0, 14)}.example`,
  phone: `+${rng.int(31, 49)} ${rng.int(10, 99)} ${rng.int(1000000, 9999999)}`,
  address: { line1: `${rng.int(1, 240)} ${rng.pick(['Industrial Way', 'Harbour Road', 'Station Street', 'Park Avenue', 'Mill Lane'])}`, city, country },
  taxId: `${country}${rng.int(100000000, 999999999)}`,
  paymentTerms: PAYMENT_TERMS[terms],
  creditLimit: money(credit),
  balance: zero(),
  salesRepId: SALES_REPS[i % SALES_REPS.length]!.id,
  active: i !== 14, // one archived customer, so the UI has to handle inactive rows
  ...stamps(daysAgo(300 - i * 4), U['u-3']!),
}));

const SUPPLIER_SEEDS: [string, string, string, keyof typeof PAYMENT_TERMS, number][] = [
  ['Vulkan Kabelwerke GmbH', 'Cologne', 'DE', 'net_45', 21],
  ['Schneider Components Benelux', 'Eindhoven', 'NL', 'net_30', 14],
  ['Lucent Lighting Industries', 'Milan', 'IT', 'net_30', 28],
  ['ProSecure Circuit Systems', 'Barcelona', 'ES', 'net_45', 18],
  ['Baltic Steel Enclosures OÜ', 'Tallinn', 'EE', 'net_60', 35],
  ['Kraft Tools International', 'Solingen', 'DE', 'net_30', 12],
  ['Nordwire Cable Trading', 'Gothenburg', 'SE', 'net_30', 16],
  ['Union Conduit & Trunking Ltd', 'Sheffield', 'GB', 'net_30', 10],
  ['Helios Optoelectronics', 'Shenzhen', 'CN', 'immediate', 45],
  ['Fixings & Fasteners Direct', 'Venlo', 'NL', 'net_15', 7],
];

export const SUPPLIERS: Supplier[] = SUPPLIER_SEEDS.map(([name, city, country, terms, lead], i) => ({
  id: `s-${pad(i + 1, 3)}`,
  code: `SUPP-${pad(i + 1)}`,
  name,
  type: 'supplier' as const,
  email: `orders@${name.toLowerCase().replace(/[^a-z]+/g, '').slice(0, 14)}.example`,
  phone: `+${rng.int(31, 86)} ${rng.int(10, 99)} ${rng.int(1000000, 9999999)}`,
  address: { line1: `${rng.int(1, 180)} ${rng.pick(['Werkstrasse', 'Havenweg', 'Via Industria', 'Poligono Norte', 'Export Road'])}`, city, country },
  taxId: `${country}${rng.int(100000000, 999999999)}`,
  paymentTerms: PAYMENT_TERMS[terms],
  balance: zero(),
  leadTimeDays: lead,
  active: true,
  ...stamps(daysAgo(320 - i * 6), U['u-5']!),
}));

/** Which supplier we normally buy each category from. Drives reorder suggestions. */
const CATEGORY_SUPPLIER: Record<string, string> = {
  'cat-1': 's-001',
  'cat-2': 's-004',
  'cat-3': 's-003',
  'cat-4': 's-005',
  'cat-5': 's-006',
  'cat-6': 's-010',
};

// ===========================================================================
// MUTABLE COLLECTIONS the generator fills
// ===========================================================================

export const SALES_ORDERS: SalesOrder[] = [];
export const DELIVERIES: Delivery[] = [];
export const CUSTOMER_INVOICES: CustomerInvoice[] = [];
export const PURCHASE_ORDERS: PurchaseOrder[] = [];
export const GOODS_RECEIPTS: GoodsReceipt[] = [];
export const SUPPLIER_BILLS: import('@/domain').SupplierBill[] = [];
export const PAYMENTS: Payment[] = [];
export const STOCK_MOVES: StockMove[] = [];
export const JOURNAL_ENTRIES: JournalEntry[] = [];
export const AUDIT_EVENTS: AuditEvent[] = [];
export const ADJUSTMENTS: InventoryAdjustment[] = [];

let jeCounter = 0;
let moveCounter = 0;
let auditCounter = 0;

function docRef(d: { id: string; docNumber: string }, docType: DocumentRef['docType']): DocumentRef {
  return { id: d.id, docType, docNumber: d.docNumber };
}

function audit(
  occurredAt: Date,
  actor: UserRef,
  action: AuditEvent['action'],
  target: AuditEvent['target'],
  summary: string,
  changes?: AuditEvent['changes'],
) {
  const user = USERS.find((u) => u.id === actor.id)!;
  AUDIT_EVENTS.push({
    id: `ae-${pad(++auditCounter, 5)}`,
    occurredAt: toISODateTime(occurredAt),
    actor,
    actorRole: user.roleKey,
    action,
    target,
    summary,
    changes,
    ipAddress: `10.4.${rng.int(1, 6)}.${rng.int(20, 210)}`,
  });
}

function stockMove(
  product: Product,
  warehouseId: string,
  quantity: number,
  reason: StockMove['reason'],
  unitCost: Money,
  at: Date,
  source: DocumentRef,
  by: UserRef,
) {
  const wh = WAREHOUSES.find((w) => w.id === warehouseId)!;
  STOCK_MOVES.push({
    id: `sm-${pad(++moveCounter, 5)}`,
    productId: product.id,
    productSku: product.sku,
    productName: product.name,
    warehouseId,
    warehouseName: wh.name,
    quantity,
    reason,
    unitCost,
    occurredAt: toISODateTime(at),
    sourceDocument: source,
    createdBy: by,
  });
}

/**
 * Create a balanced journal entry.
 * Throws if it does not balance — a guard that catches fixture bugs immediately,
 * and mirrors the constraint a real backend must enforce.
 */
function journal(
  entryDate: Date,
  memo: string,
  rawLines: { code: string; debit?: number; credit?: number; party?: { id: string; name: string }; description?: string }[],
  source: DocumentRef | undefined,
  by: UserRef,
  origin: 'system' | 'manual' = 'system',
): JournalEntry {
  const lines: JournalLine[] = rawLines.map((l, i) => {
    const acc = ACCOUNT_BY_CODE.get(l.code)!;
    return {
      id: `jl-${pad(jeCounter + 1, 5)}-${i}`,
      accountId: acc.id,
      accountCode: acc.code,
      accountName: acc.name,
      description: l.description,
      debit: money(l.debit ?? 0),
      credit: money(l.credit ?? 0),
      partyId: l.party?.id,
      partyName: l.party?.name,
    };
  });

  const totalDebit = sum(lines.map((l) => l.debit));
  const totalCredit = sum(lines.map((l) => l.credit));
  if (totalDebit.amount !== totalCredit.amount) {
    throw new Error(`Unbalanced journal entry "${memo}": ${totalDebit.amount} vs ${totalCredit.amount}`);
  }

  const entry: JournalEntry = {
    id: `je-${pad(++jeCounter, 5)}`,
    docNumber: `JE-2026-${pad(jeCounter)}`,
    docType: 'journal_entry',
    status: 'posted',
    entryDate: toISODate(entryDate),
    memo,
    lines,
    totalDebit,
    totalCredit,
    sourceDocument: source,
    origin,
    postedAt: toISODateTime(entryDate),
    postedBy: U['u-7']!,
    links: source ? [source] : [],
    ...stamps(entryDate, by),
  };
  JOURNAL_ENTRIES.push(entry);
  return entry;
}

// ===========================================================================
// OPENING STOCK
// ===========================================================================
/**
 * Every product starts with an opening balance recorded as a movement, not as a
 * magic starting number on the product. Even "day one" stock has a document.
 */
const OPENING_REF: DocumentRef = { id: 'adj-open', docType: 'inventory_adjustment', docNumber: 'ADJ-2026-0001' };

for (const product of STOCKABLE) {
  for (const wh of WAREHOUSES) {
    const base = product.reorderPoint * (wh.isDefault ? 2.6 : 0.9);
    const qty = Math.round(base * rng.float(0.7, 1.35));
    if (qty <= 0) continue;
    stockMove(product, wh.id, qty, 'adjustment', product.costPrice, daysAgo(180), OPENING_REF, U['u-6']!);
  }
}

ADJUSTMENTS.push({
  id: 'adj-open',
  docNumber: 'ADJ-2026-0001',
  docType: 'inventory_adjustment',
  status: 'posted',
  warehouseId: 'wh-1',
  warehouseName: WAREHOUSES[0]!.name,
  countDate: toISODate(daysAgo(180)),
  reason: 'annual_count',
  lines: [],
  links: [],
  notes: 'Opening stock balances migrated at system go-live.',
  ...stamps(daysAgo(180), U['u-1']!),
});

// ===========================================================================
// PURCHASE CYCLE
// ===========================================================================

let poCounter = 0;
let grCounter = 0;
let billCounter = 0;
let payCounter = 0;

const PO_PLAN: { daysBack: number; status: PurchaseOrderStatus }[] = [
  ...Array.from({ length: 14 }, (_, i) => ({ daysBack: 150 - i * 9, status: 'billed' as PurchaseOrderStatus })),
  ...Array.from({ length: 6 }, (_, i) => ({ daysBack: 40 - i * 5, status: 'received' as PurchaseOrderStatus })),
  ...Array.from({ length: 4 }, (_, i) => ({ daysBack: 22 - i * 4, status: 'partially_received' as PurchaseOrderStatus })),
  ...Array.from({ length: 5 }, (_, i) => ({ daysBack: 14 - i * 2, status: 'approved' as PurchaseOrderStatus })),
  ...Array.from({ length: 4 }, (_, i) => ({ daysBack: 6 - i, status: 'pending_approval' as PurchaseOrderStatus })),
  ...Array.from({ length: 3 }, (_, i) => ({ daysBack: 3 - i, status: 'draft' as PurchaseOrderStatus })),
  { daysBack: 30, status: 'cancelled' },
];

for (const plan of PO_PLAN) {
  const supplier = rng.pick(SUPPLIERS);
  const orderedAt = daysAgo(plan.daysBack);
  const warehouse = rng.chance(0.75) ? WAREHOUSES[0]! : WAREHOUSES[1]!;

  // Buy products this supplier plausibly sells.
  const supplierCategories = Object.entries(CATEGORY_SUPPLIER)
    .filter(([, sid]) => sid === supplier.id)
    .map(([cid]) => cid);
  const pool = supplierCategories.length
    ? STOCKABLE.filter((p) => supplierCategories.includes(p.categoryId))
    : STOCKABLE;
  const picks = rng.sample(pool.length >= 3 ? pool : STOCKABLE, rng.int(2, 5));

  const lines: PurchaseOrderLine[] = picks.map((p, i) => {
    const quantity = Math.max(10, Math.round(p.reorderQuantity * rng.float(0.4, 1.1)));
    const unitCost = multiply(p.costPrice, rng.float(0.96, 1.05));
    const lineSubtotal = multiply(unitCost, quantity);
    const lineTax = percentOf(lineSubtotal, VAT_RATE);
    return {
      id: `pol-${pad(poCounter + 1)}-${i}`,
      productId: p.id,
      productSku: p.sku,
      productName: p.name,
      quantity,
      unitCost,
      taxRatePercent: VAT_RATE,
      lineSubtotal,
      lineTax,
      lineTotal: add(lineSubtotal, lineTax),
      receivedQuantity: 0,
      billedQuantity: 0,
    };
  });

  const subtotal = sum(lines.map((l) => l.lineSubtotal));
  const taxTotal = sum(lines.map((l) => l.lineTax));
  const total = add(subtotal, taxTotal);

  const po: PurchaseOrder = {
    id: `po-${pad(++poCounter, 3)}`,
    docNumber: `PO-2026-${pad(poCounter)}`,
    docType: 'purchase_order',
    status: plan.status,
    supplier: { id: supplier.id, name: supplier.name, type: 'supplier' },
    orderDate: toISODate(orderedAt),
    expectedDate: addDays(toISODate(orderedAt), supplier.leadTimeDays),
    warehouseId: warehouse.id,
    warehouseName: warehouse.name,
    requestedBy: U['u-5']!,
    lines,
    subtotal,
    taxTotal,
    total,
    currency: 'USD',
    billedTotal: zero(),
    links: [],
    ...stamps(orderedAt, U['u-5']!),
  };

  audit(orderedAt, U['u-5']!, 'created', docRef(po, 'purchase_order'), `Created purchase order ${po.docNumber} for ${supplier.name}`);

  const isApproved = !['draft', 'pending_approval', 'cancelled'].includes(plan.status);
  if (isApproved) {
    const approvedAt = daysAgo(plan.daysBack - 1);
    po.approvedBy = U['u-2']!;
    po.approvedAt = toISODateTime(approvedAt);
    audit(approvedAt, U['u-2']!, 'approved', docRef(po, 'purchase_order'), `Approved purchase order ${po.docNumber}`);
  }

  if (plan.status === 'cancelled') {
    audit(daysAgo(plan.daysBack - 2), U['u-2']!, 'cancelled', docRef(po, 'purchase_order'), `Cancelled purchase order ${po.docNumber}`);
  }

  // ---- Goods receipt --------------------------------------------------
  const receives = ['partially_received', 'received', 'billed'].includes(plan.status);
  if (receives) {
    const partial = plan.status === 'partially_received';
    const receivedAt = daysAgo(Math.max(0, plan.daysBack - supplier.leadTimeDays));

    const gr: GoodsReceipt = {
      id: `gr-${pad(++grCounter, 3)}`,
      docNumber: `GR-2026-${pad(grCounter)}`,
      docType: 'goods_receipt',
      status: 'received',
      supplier: po.supplier,
      purchaseOrderId: po.id,
      purchaseOrderNumber: po.docNumber,
      warehouseId: po.warehouseId,
      warehouseName: po.warehouseName,
      receivedDate: toISODate(receivedAt),
      receivedBy: U['u-6']!,
      supplierDeliveryNote: `DN-${rng.int(100000, 999999)}`,
      lines: lines.map((l, i) => {
        const receivedQuantity = partial && i === 0 ? Math.floor(l.quantity * 0.6) : l.quantity;
        const rejected = rng.chance(0.06) ? Math.min(2, Math.floor(receivedQuantity * 0.02)) : 0;
        return {
          id: `grl-${pad(grCounter)}-${i}`,
          productId: l.productId,
          productSku: l.productSku,
          productName: l.productName,
          orderedQuantity: l.quantity,
          receivedQuantity,
          rejectedQuantity: rejected,
        };
      }),
      links: [docRef(po, 'purchase_order')],
      ...stamps(receivedAt, U['u-6']!),
    };
    GOODS_RECEIPTS.push(gr);
    po.links.push(docRef(gr, 'goods_receipt'));

    // Goods physically arrived -> stock moves. THIS is what changes inventory.
    for (const grl of gr.lines) {
      const product = PRODUCTS.find((p) => p.id === grl.productId)!;
      const poLine = lines.find((l) => l.productId === grl.productId)!;
      const good = grl.receivedQuantity - grl.rejectedQuantity;
      poLine.receivedQuantity = grl.receivedQuantity;
      if (good > 0) {
        stockMove(product, po.warehouseId, good, 'purchase_receipt', poLine.unitCost, receivedAt, docRef(gr, 'goods_receipt'), U['u-6']!);
      }
    }

    audit(receivedAt, U['u-6']!, 'received', docRef(gr, 'goods_receipt'), `Received goods ${gr.docNumber} against ${po.docNumber}`);

    // ---- Supplier bill ------------------------------------------------
    if (plan.status === 'billed') {
      const billedAt = daysAgo(Math.max(0, plan.daysBack - supplier.leadTimeDays - 2));
      const billDate = toISODate(billedAt);
      const dueDate = addDays(billDate, supplier.paymentTerms.daysUntilDue);
      const hasVariance = rng.chance(0.12);

      const billLines: InvoiceLine[] = lines.map((l, i) => ({
        id: `bl-${pad(billCounter + 1)}-${i}`,
        productId: l.productId,
        productSku: l.productSku,
        description: l.productName,
        quantity: l.quantity,
        unitPrice: l.unitCost,
        discountPercent: 0,
        taxRatePercent: VAT_RATE,
        lineSubtotal: l.lineSubtotal,
        lineTax: l.lineTax,
        lineTotal: l.lineTotal,
        accountCode: '1300',
      }));

      const paidFully = rng.chance(0.45);
      const paidPartly = !paidFully && rng.chance(0.35);
      const paidAmount = paidFully ? total : paidPartly ? multiply(total, 0.5) : zero();
      const balanceDue = subtract(total, paidAmount);
      const overdue = balanceDue.amount > 0 && new Date(`${dueDate}T00:00:00Z`) < REFERENCE_TODAY;

      const status: InvoiceStatus = paidFully ? 'paid' : overdue ? 'overdue' : paidPartly ? 'partially_paid' : 'posted';

      const bill: import('@/domain').SupplierBill = {
        id: `sb-${pad(++billCounter, 3)}`,
        docNumber: `BILL-2026-${pad(billCounter)}`,
        docType: 'supplier_bill',
        status,
        party: po.supplier,
        invoiceDate: billDate,
        dueDate,
        lines: billLines,
        subtotal,
        taxTotal,
        total,
        paidAmount,
        balanceDue,
        currency: 'USD',
        postedAt: toISODateTime(billedAt),
        postedBy: U['u-7']!,
        purchaseOrderIds: [po.id],
        purchaseOrderNumbers: [po.docNumber],
        supplierReference: `${supplier.code}-${rng.int(10000, 99999)}`,
        matchStatus: hasVariance ? rng.pick(['quantity_variance', 'price_variance'] as const) : 'matched',
        links: [docRef(po, 'purchase_order'), docRef(gr, 'goods_receipt')],
        ...stamps(billedAt, U['u-7']!),
      };

      // Posting the bill produces the accounting consequence.
      const je = journal(
        billedAt,
        `Supplier bill ${bill.docNumber} from ${supplier.name}`,
        [
          { code: '1300', debit: subtotal.amount / 100, description: 'Goods received into stock' },
          { code: '2100', debit: taxTotal.amount / 100, description: 'Input VAT' },
          { code: '2010', credit: total.amount / 100, party: { id: supplier.id, name: supplier.name } },
        ],
        docRef(bill, 'supplier_bill'),
        U['u-7']!,
      );
      bill.journalEntryId = je.id;
      bill.journalEntryNumber = je.docNumber;
      bill.links.push(docRef(je, 'journal_entry'));

      SUPPLIER_BILLS.push(bill);
      po.status = 'billed';
      po.billedTotal = total;
      po.links.push(docRef(bill, 'supplier_bill'));
      for (const l of lines) l.billedQuantity = l.quantity;

      audit(billedAt, U['u-7']!, 'posted', docRef(bill, 'supplier_bill'), `Posted supplier bill ${bill.docNumber} for ${supplier.name}`);

      // ---- Supplier payment -------------------------------------------
      if (paidAmount.amount > 0) {
        const paidAt = daysAgo(Math.max(0, plan.daysBack - supplier.leadTimeDays - 2 - rng.int(5, 25)));
        const cashAccount = rng.pick(CASH_ACCOUNTS.filter((a) => a.code !== '1030'));
        const allocation: PaymentAllocation = {
          invoiceId: bill.id,
          invoiceNumber: bill.docNumber,
          amountApplied: paidAmount,
        };

        const payment: Payment = {
          id: `pay-${pad(++payCounter, 3)}`,
          docNumber: `PAY-OUT-${pad(payCounter)}`,
          docType: 'supplier_payment',
          status: 'posted',
          direction: 'outbound',
          party: po.supplier,
          paymentDate: toISODate(paidAt),
          method: rng.pick(['bank_transfer', 'bank_transfer', 'cheque'] as const),
          amount: paidAmount,
          currency: 'USD',
          cashAccountId: cashAccount.id,
          cashAccountName: cashAccount.name,
          reference: `SEPA-${rng.int(1000000, 9999999)}`,
          allocations: [allocation],
          unallocatedAmount: zero(),
          links: [docRef(bill, 'supplier_bill')],
          ...stamps(paidAt, U['u-7']!),
        };

        const payJe = journal(
          paidAt,
          `Payment to ${supplier.name} for ${bill.docNumber}`,
          [
            { code: '2010', debit: paidAmount.amount / 100, party: { id: supplier.id, name: supplier.name } },
            { code: cashAccount.code, credit: paidAmount.amount / 100 },
          ],
          docRef(payment, 'supplier_payment'),
          U['u-7']!,
        );
        payment.journalEntryId = payJe.id;
        payment.journalEntryNumber = payJe.docNumber;
        payment.links.push(docRef(payJe, 'journal_entry'));
        bill.links.push(docRef(payment, 'supplier_payment'));

        PAYMENTS.push(payment);
        audit(paidAt, U['u-7']!, 'paid', docRef(payment, 'supplier_payment'), `Paid ${supplier.name} against ${bill.docNumber}`);
      }
    }
  }

  PURCHASE_ORDERS.push(po);
}

// ===========================================================================
// SALES CYCLE
// ===========================================================================

let soCounter = 0;
let delCounter = 0;
let invCounter = 0;

const SO_PLAN: { daysBack: number; status: SalesOrderStatus }[] = [
  ...Array.from({ length: 34 }, (_, i) => ({ daysBack: 140 - i * 4, status: 'invoiced' as SalesOrderStatus })),
  ...Array.from({ length: 8 }, (_, i) => ({ daysBack: 26 - i * 3, status: 'delivered' as SalesOrderStatus })),
  ...Array.from({ length: 5 }, (_, i) => ({ daysBack: 12 - i * 2, status: 'partially_delivered' as SalesOrderStatus })),
  ...Array.from({ length: 7 }, (_, i) => ({ daysBack: 9 - i, status: 'confirmed' as SalesOrderStatus })),
  ...Array.from({ length: 4 }, (_, i) => ({ daysBack: 2 - i * 0.5, status: 'draft' as SalesOrderStatus })),
  { daysBack: 18, status: 'cancelled' },
  { daysBack: 45, status: 'cancelled' },
];

for (const plan of SO_PLAN) {
  const customer = rng.pick(CUSTOMERS.filter((c) => c.active));
  const orderedAt = daysAgo(Math.round(plan.daysBack));
  const rep = SALES_REPS.find((r) => r.id === customer.salesRepId) ?? SALES_REPS[0]!;
  const warehouse = rng.chance(0.8) ? WAREHOUSES[0]! : WAREHOUSES[1]!;

  const picks = rng.sample(PRODUCTS.filter((p) => p.active), rng.int(2, 6));

  const lines: SalesOrderLine[] = picks.map((p, i) => {
    // Trade customers buy in bulk, so order quantities scale with how fast the
    // product moves (its reorder point) rather than being a flat small number.
    const quantity = p.type === 'service' ? 1 : rng.int(6, Math.max(14, Math.round(p.reorderPoint * 0.45)));
    const discountPercent = rng.chance(0.3) ? rng.pick([2.5, 5, 7.5, 10]) : 0;
    const gross = multiply(p.salesPrice, quantity);
    const lineSubtotal = subtract(gross, percentOf(gross, discountPercent));
    const lineTax = percentOf(lineSubtotal, VAT_RATE);
    return {
      id: `sol-${pad(soCounter + 1)}-${i}`,
      productId: p.id,
      productSku: p.sku,
      productName: p.name,
      quantity,
      unitPrice: p.salesPrice,
      discountPercent,
      taxRatePercent: VAT_RATE,
      lineSubtotal,
      lineTax,
      lineTotal: add(lineSubtotal, lineTax),
      deliveredQuantity: 0,
      invoicedQuantity: 0,
    };
  });

  const subtotal = sum(lines.map((l) => l.lineSubtotal));
  const taxTotal = sum(lines.map((l) => l.lineTax));
  const total = add(subtotal, taxTotal);

  const so: SalesOrder = {
    id: `so-${pad(++soCounter, 3)}`,
    docNumber: `SO-2026-${pad(soCounter)}`,
    docType: 'sales_order',
    status: plan.status,
    customer: { id: customer.id, name: customer.name, type: 'customer' },
    orderDate: toISODate(orderedAt),
    expectedDeliveryDate: addDays(toISODate(orderedAt), rng.int(3, 12)),
    warehouseId: warehouse.id,
    warehouseName: warehouse.name,
    salesRep: ref(rep),
    lines,
    subtotal,
    taxTotal,
    total,
    currency: 'USD',
    invoicedTotal: zero(),
    links: [],
    ...stamps(orderedAt, ref(rep)),
  };

  audit(orderedAt, ref(rep), 'created', docRef(so, 'sales_order'), `Created sales order ${so.docNumber} for ${customer.name}`);

  if (plan.status === 'cancelled') {
    audit(daysAgo(Math.round(plan.daysBack) - 1), ref(rep), 'cancelled', docRef(so, 'sales_order'), `Cancelled sales order ${so.docNumber}`);
    SALES_ORDERS.push(so);
    continue;
  }

  if (plan.status !== 'draft') {
    audit(orderedAt, ref(rep), 'confirmed', docRef(so, 'sales_order'), `Confirmed sales order ${so.docNumber} for ${customer.name}`);
  }

  // ---- Delivery ---------------------------------------------------------
  const ships = ['partially_delivered', 'delivered', 'invoiced'].includes(plan.status);
  if (ships) {
    const partial = plan.status === 'partially_delivered';
    const shippedAt = daysAgo(Math.max(0, Math.round(plan.daysBack) - rng.int(2, 6)));
    const stockLines = lines.filter((l) => PRODUCTS.find((p) => p.id === l.productId)!.type === 'stockable');

    const delLines: DeliveryLine[] = stockLines.map((l, i) => ({
      id: `dl-${pad(delCounter + 1)}-${i}`,
      productId: l.productId,
      productSku: l.productSku,
      productName: l.productName,
      orderedQuantity: l.quantity,
      shippedQuantity: partial && i === 0 ? Math.floor(l.quantity * 0.5) : l.quantity,
    }));

    if (delLines.length) {
      const delivery: Delivery = {
        id: `del-${pad(++delCounter, 3)}`,
        docNumber: `DEL-2026-${pad(delCounter)}`,
        docType: 'delivery',
        status: 'delivered',
        customer: so.customer,
        salesOrderId: so.id,
        salesOrderNumber: so.docNumber,
        warehouseId: so.warehouseId,
        warehouseName: so.warehouseName,
        scheduledDate: so.expectedDeliveryDate!,
        shippedDate: toISODate(shippedAt),
        carrier: rng.pick(['DHL Freight', 'DB Schenker', 'Own Fleet', 'GLS']),
        trackingNumber: `TRK${rng.int(10000000, 99999999)}`,
        lines: delLines,
        links: [docRef(so, 'sales_order')],
        ...stamps(shippedAt, U['u-6']!),
      };
      DELIVERIES.push(delivery);
      so.links.push(docRef(delivery, 'delivery'));

      let cogs = zero();
      for (const dl of delLines) {
        const product = PRODUCTS.find((p) => p.id === dl.productId)!;
        const line = lines.find((l) => l.productId === dl.productId)!;
        line.deliveredQuantity = dl.shippedQuantity;
        stockMove(product, so.warehouseId, -dl.shippedQuantity, 'sales_delivery', product.costPrice, shippedAt, docRef(delivery, 'delivery'), U['u-6']!);
        cogs = add(cogs, multiply(product.costPrice, dl.shippedQuantity));
      }

      // Shipping goods is an ACCOUNTING event too: value leaves inventory and
      // becomes cost of goods sold. Revenue is recognised separately, at invoice.
      if (cogs.amount > 0) {
        journal(
          shippedAt,
          `Cost of goods sold for ${delivery.docNumber}`,
          [
            { code: '5010', debit: cogs.amount / 100, description: 'Goods shipped to customer' },
            { code: '1300', credit: cogs.amount / 100 },
          ],
          docRef(delivery, 'delivery'),
          U['u-7']!,
        );
      }

      audit(shippedAt, U['u-6']!, 'shipped', docRef(delivery, 'delivery'), `Shipped ${delivery.docNumber} for ${so.docNumber}`);
    }
  }

  // ---- Invoice ----------------------------------------------------------
  if (plan.status === 'invoiced') {
    const invoicedAt = daysAgo(Math.max(0, Math.round(plan.daysBack) - rng.int(6, 10)));
    const invoiceDate = toISODate(invoicedAt);
    const dueDate = addDays(invoiceDate, customer.paymentTerms.daysUntilDue);

    const invLines: InvoiceLine[] = lines.map((l, i) => ({
      id: `il-${pad(invCounter + 1)}-${i}`,
      productId: l.productId,
      productSku: l.productSku,
      description: l.productName,
      quantity: l.quantity,
      unitPrice: l.unitPrice,
      discountPercent: l.discountPercent,
      taxRatePercent: VAT_RATE,
      lineSubtotal: l.lineSubtotal,
      lineTax: l.lineTax,
      lineTotal: l.lineTotal,
      accountCode: '4010',
    }));

    // Collection profile. Tuned so the receivables ledger carries a realistic
    // amount of unpaid balance: a distributor selling on Net 30–60 terms always
    // has a substantial book of money owed. If almost everything were marked
    // paid, the aging chart and the overdue alerts would have nothing to show
    // and the dashboard would misrepresent how this kind of business runs.
    const roll = rng.next();
    const paidFully = roll < 0.34;
    const paidPartly = !paidFully && roll < 0.6;
    const paidAmount = paidFully ? total : paidPartly ? multiply(total, rng.float(0.3, 0.7)) : zero();
    const balanceDue = subtract(total, paidAmount);
    const overdue = balanceDue.amount > 0 && new Date(`${dueDate}T00:00:00Z`) < REFERENCE_TODAY;
    const status: InvoiceStatus = paidFully ? 'paid' : overdue ? 'overdue' : paidPartly ? 'partially_paid' : 'posted';

    const invoice: CustomerInvoice = {
      id: `ci-${pad(++invCounter, 3)}`,
      docNumber: `INV-2026-${pad(invCounter)}`,
      docType: 'customer_invoice',
      status,
      party: so.customer,
      invoiceDate,
      dueDate,
      lines: invLines,
      subtotal,
      taxTotal,
      total,
      paidAmount,
      balanceDue,
      currency: 'USD',
      postedAt: toISODateTime(invoicedAt),
      postedBy: U['u-7']!,
      salesOrderIds: [so.id],
      salesOrderNumbers: [so.docNumber],
      links: [docRef(so, 'sales_order')],
      ...stamps(invoicedAt, U['u-7']!),
    };

    const je = journal(
      invoicedAt,
      `Customer invoice ${invoice.docNumber} for ${customer.name}`,
      [
        { code: '1200', debit: total.amount / 100, party: { id: customer.id, name: customer.name } },
        { code: '4010', credit: subtotal.amount / 100, description: 'Product sales' },
        { code: '2100', credit: taxTotal.amount / 100, description: 'Output VAT' },
      ],
      docRef(invoice, 'customer_invoice'),
      U['u-7']!,
    );
    invoice.journalEntryId = je.id;
    invoice.journalEntryNumber = je.docNumber;
    invoice.links.push(docRef(je, 'journal_entry'));

    /**
     * The order carries the WHOLE downstream trail, not just its direct
     * children. Strictly, the journal entry belongs to the invoice and the
     * invoice belongs to the order. But the question a user asks standing on an
     * order is "what happened to this in the end", and making them hop through
     * three screens to answer it is exactly the friction an ERP should remove.
     * Real systems denormalise the trail for the same reason.
     */
    so.links.push(docRef(je, 'journal_entry'));

    CUSTOMER_INVOICES.push(invoice);
    so.invoicedTotal = total;
    so.links.push(docRef(invoice, 'customer_invoice'));
    for (const l of lines) l.invoicedQuantity = l.quantity;

    audit(invoicedAt, U['u-7']!, 'posted', docRef(invoice, 'customer_invoice'), `Posted invoice ${invoice.docNumber} for ${customer.name}`);

    if (paidAmount.amount > 0) {
      const paidAt = daysAgo(Math.max(0, Math.round(plan.daysBack) - rng.int(11, 40)));
      const cashAccount = rng.pick(CASH_ACCOUNTS.filter((a) => a.code !== '1030'));
      const payment: Payment = {
        id: `pay-${pad(++payCounter, 3)}`,
        docNumber: `PAY-IN-${pad(payCounter)}`,
        docType: 'customer_payment',
        status: 'posted',
        direction: 'inbound',
        party: so.customer,
        paymentDate: toISODate(paidAt),
        method: rng.pick(['bank_transfer', 'bank_transfer', 'bank_transfer', 'card', 'cheque'] as const),
        amount: paidAmount,
        currency: 'USD',
        cashAccountId: cashAccount.id,
        cashAccountName: cashAccount.name,
        reference: `RCPT-${rng.int(1000000, 9999999)}`,
        allocations: [{ invoiceId: invoice.id, invoiceNumber: invoice.docNumber, amountApplied: paidAmount }],
        unallocatedAmount: zero(),
        links: [docRef(invoice, 'customer_invoice')],
        ...stamps(paidAt, U['u-7']!),
      };

      const payJe = journal(
        paidAt,
        `Receipt from ${customer.name} for ${invoice.docNumber}`,
        [
          { code: cashAccount.code, debit: paidAmount.amount / 100 },
          { code: '1200', credit: paidAmount.amount / 100, party: { id: customer.id, name: customer.name } },
        ],
        docRef(payment, 'customer_payment'),
        U['u-7']!,
      );
      payment.journalEntryId = payJe.id;
      payment.journalEntryNumber = payJe.docNumber;
      payment.links.push(docRef(payJe, 'journal_entry'));
      invoice.links.push(docRef(payment, 'customer_payment'));
      so.links.push(docRef(payment, 'customer_payment'));

      PAYMENTS.push(payment);
      audit(paidAt, U['u-7']!, 'paid', docRef(payment, 'customer_payment'), `Received ${customer.name} payment against ${invoice.docNumber}`);
    }
  }

  SALES_ORDERS.push(so);
}

// ===========================================================================
// A FEW EXTRAS so the UI has edge cases to render honestly
// ===========================================================================

// One unallocated customer payment: money arrived that nobody has matched to an
// invoice yet. Real finance teams always have a few of these, and they must be
// visible or the cash goes unexplained.
{
  const customer = CUSTOMERS[5]!;
  const paidAt = daysAgo(3);
  const amount = money(12_500);
  const cashAccount = CASH_ACCOUNTS[1]!;
  const payment: Payment = {
    id: `pay-${pad(++payCounter, 3)}`,
    docNumber: `PAY-IN-${pad(payCounter)}`,
    docType: 'customer_payment',
    status: 'posted',
    direction: 'inbound',
    party: { id: customer.id, name: customer.name, type: 'customer' },
    paymentDate: toISODate(paidAt),
    method: 'bank_transfer',
    amount,
    currency: 'USD',
    cashAccountId: cashAccount.id,
    cashAccountName: cashAccount.name,
    reference: 'SEPA-INBOUND-8841720',
    allocations: [],
    unallocatedAmount: amount,
    notes: 'Received on account. Remittance advice not yet supplied by customer.',
    links: [],
    ...stamps(paidAt, U['u-7']!),
  };
  const je = journal(
    paidAt,
    `Receipt on account from ${customer.name}`,
    [
      { code: cashAccount.code, debit: 12_500 },
      { code: '1200', credit: 12_500, party: { id: customer.id, name: customer.name } },
    ],
    docRef(payment, 'customer_payment'),
    U['u-7']!,
  );
  payment.journalEntryId = je.id;
  payment.journalEntryNumber = je.docNumber;
  PAYMENTS.push(payment);
  audit(paidAt, U['u-7']!, 'paid', docRef(payment, 'customer_payment'), `Recorded unallocated receipt from ${customer.name}`);
}

// A stock adjustment after a cycle count, with the shrinkage posted to expense.
{
  const countedAt = daysAgo(9);
  const picks = rng.sample(STOCKABLE, 4);
  const adj: InventoryAdjustment = {
    id: 'adj-002',
    docNumber: 'ADJ-2026-0002',
    docType: 'inventory_adjustment',
    status: 'posted',
    warehouseId: 'wh-1',
    warehouseName: WAREHOUSES[0]!.name,
    countDate: toISODate(countedAt),
    reason: 'cycle_count',
    lines: [],
    links: [],
    notes: 'Quarterly cycle count, aisle C.',
    ...stamps(countedAt, U['u-6']!),
  };

  let shrinkage = zero();
  picks.forEach((p, i) => {
    const difference = rng.pick([-3, -2, -1, 1, -5]);

    // What the system believed was on the shelf at the moment of the count:
    // the sum of every movement for this product and warehouse recorded before
    // then. Derived from the ledger rather than stored, exactly like the stock
    // projection, so the variance the adjustment reports is a real subtraction.
    const countedAtISO = toISODateTime(countedAt);
    const systemQuantity = STOCK_MOVES.filter(
      (m) => m.productId === p.id && m.warehouseId === 'wh-1' && m.occurredAt <= countedAtISO,
    ).reduce((total, m) => total + m.quantity, 0);

    adj.lines.push({
      id: `adjl-2-${i}`,
      productId: p.id,
      productSku: p.sku,
      productName: p.name,
      systemQuantity,
      countedQuantity: systemQuantity + difference,
      difference,
    });
    stockMove(p, 'wh-1', difference, 'adjustment', p.costPrice, countedAt, docRef(adj, 'inventory_adjustment'), U['u-6']!);
    if (difference < 0) shrinkage = add(shrinkage, multiply(p.costPrice, -difference));
  });

  if (shrinkage.amount > 0) {
    journal(
      countedAt,
      `Inventory shrinkage for ${adj.docNumber}`,
      [
        { code: '5030', debit: shrinkage.amount / 100, description: 'Cycle count variance' },
        { code: '1300', credit: shrinkage.amount / 100 },
      ],
      docRef(adj, 'inventory_adjustment'),
      U['u-7']!,
    );
  }

  ADJUSTMENTS.push(adj);
  audit(countedAt, U['u-6']!, 'posted', docRef(adj, 'inventory_adjustment'), `Posted cycle count adjustment ${adj.docNumber}`);
}

// A manual journal entry — monthly rent accrual. Manual entries have no source
// document, which is exactly why auditors look at them first.
journal(
  daysAgo(13),
  'Monthly rent and utilities accrual',
  [
    { code: '6020', debit: 5_400, description: 'August rent, Rotterdam DC' },
    { code: '2200', credit: 5_400 },
  ],
  undefined,
  U['u-7']!,
  'manual',
);

// Login and permission events, so the audit log is not only document traffic.
audit(daysAgo(0), U['u-7']!, 'logged_in', { id: 'u-7', docType: 'user', docNumber: 'elena@meridian.example' }, 'Elena Duarte signed in');
audit(daysAgo(1), U['u-2']!, 'logged_in', { id: 'u-2', docType: 'user', docNumber: 'daniel@meridian.example' }, 'Daniel Roche signed in');
audit(daysAgo(4), U['u-1']!, 'permission_changed', { id: 'u-4', docType: 'user', docNumber: 'kofi@meridian.example' },
  'Changed role for Kofi Mensah', [{ field: 'roleKey', label: 'Role', before: 'warehouse', after: 'sales' }]);
audit(daysAgo(6), U['u-1']!, 'updated', { id: 'c-003', docType: 'customer', docNumber: 'CUST-0003' },
  'Updated credit limit for Nordic Build Group AB', [
    { field: 'creditLimit', label: 'Credit limit', before: '$150,000.00', after: '$200,000.00' },
    { field: 'paymentTerms', label: 'Payment terms', before: 'Net 15', after: 'Net 30' },
  ]);
audit(daysAgo(2), U['u-1']!, 'updated', { id: 'p-007', docType: 'product', docNumber: 'MCB-0616' },
  'Updated pricing for MCB Type B 16A Single Pole', [
    { field: 'salesPrice', label: 'Sales price', before: '$7.95', after: '$8.40' },
  ]);

// Sort chronologically, newest first — the order every feed in the UI wants.
AUDIT_EVENTS.sort((a, b) => b.occurredAt.localeCompare(a.occurredAt));
STOCK_MOVES.sort((a, b) => b.occurredAt.localeCompare(a.occurredAt));
JOURNAL_ENTRIES.sort((a, b) => b.entryDate.localeCompare(a.entryDate));
